stages:
  - build
  - test


compilation:
  stage: build
  script:
    - git submodule update --init
    - sbt compile
  only:
    - master
  tags:
    - compile


testing:
  stage: test
  script:
    - git submodule update --init
    - sbt test
  only:
    - master
  tags:
    - test
    - spec2 
  allow_failure: true
